-- 코드를 입력하세요
# 자동차 종류 세단, SUV
# 기간 2022 11 1 ~ 2022 11 30
# 30일간 대여 금액 50이상 200미만
# 자동차 ID, 종류, 대여 금액(FEE)

SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE

WHERE
    C.DURATION_TYPE = '30일 이상'
    AND A.CAR_TYPE in ('세단', 'SUV')
    AND A.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01' )

GROUP BY A.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER bY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID ASC
