-- 코드를 입력하세요
SELECT YEAR(a.SALES_DATE) as YEAR, MONTH(a.SALES_DATE) as MONTH, b.GENDER, COUNT(DISTINCT b.USER_ID) as USERS
FROM ONLINE_SALE a
JOIN USER_INFO b ON a.USER_ID = b.USER_ID
WHERE b.GENDER is not null
GROUP BY YEAR(a.SALES_DATE), MONTH(a.SALES_DATE), b.GENDER
HAVING b.GENDER is not null
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC

