-- 코드를 입력하세요
SELECT CAR_ID, case when CAR_ID in (
                        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                        WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16') then '대여중' else '대여 가능' end 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID

ORDER BY CAR_ID DESC