-- 코드를 입력하세요
#SELECT MONTH(START_DATE) as MONTH, CAR_ID, COUNT(*) as RECORDS
#FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
#WHERE (SELECT * FROM )

#GROUP BY START_DATE
#HAVING YEAR(START_DATE) = '2022' AND (MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10)

#ORDER BY MONTH ASC, CAR_ID DESC

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID in (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE YEAR(START_DATE) = '2022' AND MONTH(START_DATE) >= '8' AND MONTH(START_DATE) <= '10' GROUP BY CAR_ID HAVING COUNT(*) >= 5) 
    AND YEAR(START_DATE) = '2022' AND MONTH(START_DATE) >= '8' AND MONTH(START_DATE) <= '10'
 
GROUP BY MONTH, CAR_ID
 
ORDER BY MONTH ASC, CAR_ID DESC

#SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE YEAR(START_DATE) = '2022' AND MONTH(START_DATE) >= '8' AND MONTH(START_DATE) <= '10' GROUP BY CAR_ID HAVING COUNT(*) >= 5

#SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY ORDER BY CAR_ID ASC/2 6 / 5 5 / 7 6